---
resources:
- name: my-github-repo
  type: git
  source:
    uri: https://github.com/pivotal-jamil-shamy/concourse-workshop.git
    branch: master

jobs:
- name: request-environment
  public: false
  plan:
  - get: my-github-repo
    trigger: true
  - task: task-1
    file: my-github-repo/lab-12/tasks/task-1/task.yml
- name: create-os-images
  public: false
  plan:
  - get: my-github-repo
    passed: [request-environment]
    trigger: true
  - task: task-2
    file: my-github-repo/lab-12/tasks/task-2/task.yml
- name: provision-networks
  public: false
  plan:
  - get: my-github-repo
    passed: [request-environment]
    trigger: true
  - task: task-3
    file: my-github-repo/lab-12/tasks/task-3/task.yml
- name: create-vms
  public: false
  plan:
  - get: my-github-repo
    passed: [create-os-images, provision-networks]
    trigger: true
  - task: task-4
    file: my-github-repo/lab-12/tasks/task-4/task.yml
- name: publish-environment-details
  public: false
  plan:
  - get: my-github-repo
    passed: [create-vms]
    trigger: true
  - task: task-5
    file: my-github-repo/lab-12/tasks/task-5/task.yml