platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: my-github-repo

run:
  path: my-github-repo/lab-15/tasks/task-1/run.sh

params:
  DEMO_PARAM: default-2.4.5
  DB_VERSION: "default test test"