platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: my-github-repo
- name: important-files

run:
  path: my-github-repo/lab-11/tasks/task-2/run.sh