platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 2.0

inputs:
- name: my-github-repo
- name: jamil-playlist

run:
  path: my-github-repo/lab-14/tasks/task-1/run.sh