platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: my-github-repo
- name: sample-list

run:
  path: my-github-repo/lab-14/tasks/task-1/run.sh