platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: my-github-repo
- name: jamil-playlist

run:
  path: my-github-repo/lab-14/tasks/task-1/run.sh