#!/bin/bash

# With code from https://github.com/wfernandes/vault-resource

set -Eeuo pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload="/tmp/youtube-resource-request"

# Dump stdin into a file
cat > "$payload" <&0

playlist_url=$(jq --raw-output '.source.playlist_url // ""' < "$payload")

if [ -z "$playlist_url" ]; then
  echo "invalid payload (missing playlist_url)"
  exit 1
fi

latest_video_id=$(youtube-dl -j --flat-playlist "$playlist_url" | jq -r '.id' | tail -1)

echo '{"id": "'"$latest_video_id"'"}' | jq --slurp . >&3
