#!/bin/bash

# With code from https://github.com/wfernandes/vault-resource 

set -Eeuo pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination="$1"

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>"
  exit 1
fi

payload="/tmp/youtube-resource-request"

cat > "$payload" <&0

video_to_get=$(jq -r '.version.id // ""' < "$payload")

cd "$destination"
youtube-dl "https://www.youtube.com/watch?v=${video_to_get}" --output my-video

echo '{
  "version": {
    "id": "'"$video_to_get"'"
  }
}' >&3