---
resource_types:
- name: youtube
  type: docker-image
  source:
    repository: jamlo/concourse-workshop
    tag: "3.0"

resources:
- name: my-github-repo
  type: git
  source:
    uri: https://github.com/pivotal-jamil-shamy/concourse-workshop.git
    branch: master
- name: jamil-playlist
  type: youtube
  source:
    playlist_url: "https://www.youtube.com/playlist?list=PLhpmTzt8kr78IDegM8xMnmCKzCMqcjkjA"

jobs:
- name: download-latest-video-in-playlist
  public: false
  plan:
  - get: my-github-repo
    trigger: false
  - get: jamil-playlist
    trigger: true
  - task: download-video
    file: my-github-repo/lab-14/tasks/task-1/task.yml